### ISSUE TITLE
New pods are not created or mounted

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-desktop-app#114]
### Description

working on v0.1.0-rc7 , Linux version (Linux pop-os 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux)

### To Reproduce

Using a newly created, local user, create a pod (e.g. "FirstPod"). Click, to have the pod mounted. You get an error of "cannot mount pod" on user interface.
In the terminal running the FDA, this might be relevant:

``` 
fuse: bad mount point `/home/crtah/Desktop/FDA-mount-point/Fairdrive/FourthPod': No such file or directory
```
There indeed does not exist such a folder (but would presume that the app would create it). Also, not sure if the pod was created or not.

When I closed the app and opened it again, the previously created pods were not available to select for mounting. So, maybe the pods also do not get created.

Small additional note: in the settings, the default address offfered to connect to local bee has port 1635, but should probably be 1633, as that is the API port. does not work on my machine with 1635, says it cannot connect to bee.

### Expected behaviour

Expect a created pod to be available in later sessions and to be able to mount a pod to a folder.

**Comment by tfius** [comment]
deos /FDA-mount-point/ exist ?
