### ISSUE TITLE
installation as advised on the webapge didn't work + login doesn't work on desktop

### ISSUE THREAD

**Issue by Mhardook** [fairDataSociety/fairdrive-desktop-app#124]
- At the "is your bee node running..." prompt I had to select "Yes", because it wouldn't start the installation otherwise, even though the gif on the webpage shows to select "No". I also didn't enter any batchID beacuse I don't have any postage stamps. Maybe that's the reason why "No" didn't work?

- When I tried to log into the FDA it didn't accept my password even though my account was successfully created. Same thing on the Web version. The Web version only started to work once I went through the steps with the "import account" button. I used the same login credentials as before and it suddenly worked. The desktop version still doesn't work though. It first reported an invalid password and now "no user available"

**Comment by Mhardook** [comment]
Hey, I actually did this installation because I'm writing a newsletter for the Fairdrive campaign. Črt mentioned that you are already writing installation instructions for FDA. Would you mind sharing them with me (andrej.cebokli@datafund.io). This is the doc with the current text for the instructions: https://docs.google.com/document/d/14_9HJBNDb2vQ-eOLY2_qBN8BJzlNgP_QoPi1TuKdcRs/edit?usp=sharing

Just give me the mail/ask for access and I'll add you to it if you want to take a look at it. 

What I meant with the Web version is the https://fairdrive.fairdatasociety.org/ website. The latest version of the executable worked fine without the problems of the previous version.

**Comment by tfius** [comment]
also check here https://fairdatasociety.github.io/fairdrive-desktop-app/
