### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-desktop-app#126]
### Description

Animation bug on switching toggle on Macbook Pro M1

https://user-images.githubusercontent.com/1595061/208485310-2c1f9942-6cd4-45bd-baae-56db605c900e.mov

### To Reproduce

Open app
Click by toggles

### Expected behaviour

Animation without bug

**Comment by tamas6** [comment]
reproduced bug 🪲 on an intel MBP
