### ISSUE TITLE
Sync pods manually or automatically

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairdrive-desktop-app#134]
### Is your feature request related to a problem? Please describe.

List of files and folders are cached during pod open and displayed every time we interact with the pod. If we upload something from fairdrive, we would not see the changes unless we remount.

### Describe the solution you'd like

we sync pod automatically after a certain interval, also allow user to manually sync pod.

**Comment by tfius** [comment]
600s  or 60s interval ? 
It does take some time when amount of files is big
