### ISSUE TITLE
Distorted backgroun image

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairdrive-desktop-app#139]
### Description

The background image is not displayed properly on linux version:
![Screenshot from 2023-01-09 10-34-00](https://user-images.githubusercontent.com/15090003/211286882-d9e8fa1e-80db-46f7-aa53-ffb7bd5b3a63.png)

### To Reproduce

Open any page of the app.

### Expected behaviour

The image should display properly.

**Comment by asabya** [comment]
should be fixed in next release
