### ISSUE TITLE
Check FUSE installation and display proper message

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-desktop-app#140]
### Is your feature request related to a problem? Please describe.

Check error when FUSE is not installed

### Describe the solution you'd like

Check if FUSE is available on system.
Display proper message to user where to find installation of FUSE for system.

**Comment by asabya** [comment]
![image](https://user-images.githubusercontent.com/15252513/211503614-786ce20d-898b-4f37-9aff-f2308652531b.png)
