### ISSUE TITLE
Error on copying file on Linux

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-desktop-app#171]
### Description

Trying to copy a file from one file explorer window to another on Ubuntu, i get an error.

`Error opening file “/home/crtah/Desktop/Fairdrive Desktop App/Mount-point/Fairdrive/Photos/web3pc-1.png”: Input/output error`

### To Reproduce

Open two "Files" apps on Ubuntu, one of them with the mounted pod open, the other with the source of photos
Copy one photo to mounted pod

### Expected behaviour

The copying should proceed without error.

### Screenshots

![image](https://user-images.githubusercontent.com/1554520/236202960-36161060-840a-4527-896b-89129256b446.png)

### Additional context

Ubuntu
Bee 1.15.0
Fairos desktop app 0.1.5

**Comment by asabya** [comment]
Closing it for now. Please reopen if the issue still persists.
