### ISSUE TITLE
Equip Fairdrive Desktop App with MyData operator Award Logo

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-desktop-app#174]
### Describe the solution you'd like

FDA was awarded the MyData operator 2023 award and can as such sport a MyData operator Award logo.

The logos can be found in various formats in: https://drive.google.com/drive/folders/1ztFXVWhmjXJ01VcTqi1SMn_8gje4k6LO?usp=share_link

Please equip the App itself with logo you find appropriate in appropriate size and location.
Please equip also the page with instructions with appropriate variant of the logo. 

The logo if clicked, should lead to: https://www.mydata.org/participate/awards/
The page explains about the awards.

And congratulations!

**Comment by asabya** [comment]
<img width="362" alt="image" src="https://github.com/fairDataSociety/fairdrive-desktop-app/assets/15252513/bf5d1b25-c945-46ae-a24e-6eb407ed186c">

Added the white logo in about modal. @crtahlin @tfius
