### ISSUE TITLE
no permission when opening pod drives - mac

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-desktop-app#188]
### Description

mounted the pods  by the checkbox, and navigating in finder, I wasn't able to open it, for a while

### To Reproduce

use inte mac
install latest
mount pods and navigate to root
try to open

### Expected behaviour

before it didn't prompt with this error

### Screenshots

<img width="301" alt="FDA problem" src="https://github.com/fairDataSociety/fairdrive-desktop-app/assets/81620050/c2ad204a-3f00-46b1-b980-fa97a6fa10d8">

### Attempted Fixes

WORKED: opened with the FDA ui's button to "open" and jumped into the folder. Later, it become persistent to be able to open the mounted pod folder, but for a while when I jumped out from the folder, I wasnt able to reopen 
it took like 2 minutes.

### Additional context

it may be due to syncing process cause one of the folder contains file, nevertheless it was unexpected  and unprecedented, with prevous version it didn't occured

**Comment by asabya** [comment]
should be resolved on v0.1.7
