### ISSUE TITLE
Add FAQ in help section

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairdrive-desktop-app#79]
- [ ] Why should I install fuse?
- [ ] How to connect with swarm?
- [ ] Where are my pods getting mounted?

**Comment by tamas6** [comment]
> * [ ] Where can I follow if the sync is happening?
> * [ ] Which is better, local light node, a full node on raspberry, or gateway?

**Comment by asabya** [comment]
> > * [ ]  Why macFUSE volume doesn't show pods name?
This is no longer relevent. fixed #80
