### ISSUE TITLE
files not the same in local and remote

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-desktop-app#94]
<img width="1002" alt="Screenshot 2022-12-12 at 11 24 06" src="https://user-images.githubusercontent.com/81620050/207022276-22a5af2b-5d41-45d8-b3f8-90c1b8e5444f.png">

That main.tsx, unkown origin for me,  and one point "blinked" in browser but this is what I am facing now, PodCreatedByBrowser shows thumbnails of lifePod's files, but cannot download or preview ..

**Comment by asabya** [comment]
Most likely this is related to fairdrive web app,
