### ISSUE TITLE
logout from fairdrive, and login again with different account : pod error

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-desktop-app#97]
When you do this without closing and reopening Chrome, you will see the previous PODnames, empty. 😐 Not the pods for the actual account.

**Comment by tfius** [comment]
this is fairdrive-theapp or FDA ?

**Comment by tamas6** [comment]
> this is fairdrive-theapp or FDA ?

-theapp sry

**Comment by tfius** [comment]
issue should go to that repo then
