### ISSUE TITLE
when batch ID not specified should be an alert

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-desktop-app#98]
when you do this, you'll be read only on the mounted pod, (and only can retrieve broken files, their names appear btw)

**Comment by asabya** [comment]
Specifying fairos gateways will also not require batchID... What should be the expected behaviour? @crtahlin @tfius @darkobas2

**Comment by darkobas2** [comment]
- Right now you can determine bee or gateway-proxy  by querying /health

- i dont see a problem with mounting fuse read only without a batch

**Comment by crtahlin** [comment]
I think in the original description there are a couple of issues described (you should split these into independent issues as a rule, to avoid confusion @tamas6 ).

1. what the app should do when no BatchID is specified
2. some kind of corrupt files in the pod (there would need to be more info about this to have a reproducible scenario that a developer can tackle).

Unless further information is given (in a separate issue, @tamas6 ? ), we can only tackle number 1 here.

I am inclined not to change the logic for the release we have now, but only have a warning somewhere "Without providing stampID(batchID?) you will not be able to write to Fairdrive."

In the longer run, what @darkobas2 has suggested, with the added note 
"if user doesnt enter a batch OR checkbox that stamp is provided by gateway is TRUE, you should fuse mount read only"

**Comment by tamas6** [comment]
made a separate issue #100

**Comment by tfius** [comment]
> i would suggest a checkbox like.. stamp provided by gateway and then disable batch field.

this looks like a good solution

**Comment by tfius** [comment]
> I am inclined not to change the logic for the release we have now, but only have a warning somewhere "Without providing stampID(batchID?) you will not be able to write to Fairdrive."

we shall add this for now

**Comment by asabya** [comment]
If the user does not specify "batchID", we mount as ReadOnly.
